### ISSUE TITLE
Incorrectly finds path if the folder "Wuthering Waves" is on a different drive to "Wuthering Waves Game"

### ISSUE THREAD

**Issue by EllaElla1** [alpharmi/wuthering.app#1]
Found that when it tried to find my folder, it correctly found the location that the launcher was installed to at D:\Wuthering Waves (and so did not ask me for the game install path), but then failed to find the file, as my "Wuthering Waves Game" folder was in a different drive and buried in other folders.

![image](https://github.com/alpharmi/wuthering.app/assets/138311927/144369d6-b506-4abe-accb-0baddde2b8ec)

**Comment by alpharmi** [comment]
It should prompt you to ask for a directory now.
Let me know how it goes.

**Comment by Miguelcmps** [comment]
> It should prompt you to ask for a directory now. Let me know how it goes.

Well, on my end (also have 2 disk set up), the Gach Url is never found even thought the path was.

![image](https://github.com/alpharmi/wuthering.app/assets/24736244/c2c095b7-dbcd-4d8b-9fa3-e84a02d42295)

**Comment by alpharmi** [comment]
@Miguelcmps Do you mind taking a screenshot of within "Wuthering Waves Game" folder if possible?

**Comment by Miguelcmps** [comment]
> @Miguelcmps Do you mind taking a screenshot of within "Wuthering Waves Game" folder if possible?

![image](https://github.com/alpharmi/wuthering.app/assets/24736244/0dc24998-dbed-498e-9268-bf784d462ed5)

I tested several ways to type the location on banners which I had history and same error

**Comment by alpharmi** [comment]
I don't see why it wouldn't be finding the log file. 
Can you check that you can reach this directory and that `debug.log` exists?
`Install Folder\Wuthering Waves Game\Client\Binaries\Win64\ThirdParty\KrPcSdk_Global\KRSDKRes\KRSDKWebView`
I also assume you've double checked and actually open the log in game.

If all else doesn't work I've recently added a second method to the site that lets u just upload the file if you'd like to try that instead.

If possible, let me know what you find, thanks for helping.

**Comment by Miguelcmps** [comment]
> I don't see why it wouldn't be finding the log file. Can you check that you can reach this directory and that `debug.log` exists? `Install Folder\Wuthering Waves Game\Client\Binaries\Win64\ThirdParty\KrPcSdk_Global\KRSDKRes\KRSDKWebView` I also assume you've double checked and actually open the log in game.
> 
> If all else doesn't work I've recently added a second method to the site that lets u just upload the file if you'd like to try that instead.
> 
> If possible, let me know what you find, thanks for helping.
> 
> @Miguelcmps

The only thing I didnt do was restart the game. I'll try that as well.

**Comment by EllaElla1** [comment]
> It should prompt you to ask for a directory now. Let me know how it goes.

![image](https://github.com/alpharmi/wuthering.app/assets/138311927/6c7597ec-4583-45d3-ac9e-e795f8863ce9)

It now prompts me correctly, but then cant find the folder as my "Wuthering Waves Game" folder isn't in a folder called "Wuthering Waves", just a generic seperate folder, so then it doesnt detect that the folder is correct, and so it doesn't update $gamePath, but then carries on anyway

**Comment by alpharmi** [comment]
@EllaElla1 It's quite difficult for me to find the game installation cause unfortunately Wuthering Waves doesn't output somewhere where the game is located so I have to find it manually. There's not much more I can do it automatically find your installation sorry unless I add a complete direct path option or you can just use method 2 which I've recently added to the website that lets you upload the debug.log directly.

**Comment by Miguelcmps** [comment]
@alpharmi Hey.

In a fresh restart, I looked for a generic path and the literal directory of debug.log (which exists and is updated, as you can see the history open in the back of the screenshot). None were able to find the document.

The second method is working perfectly, thank you!

![image](https://github.com/alpharmi/wuthering.app/assets/24736244/791d1b98-24f0-44b0-92fb-b0b77478249d)

Let me know if I can help with.

**Comment by alpharmi** [comment]
@Miguelcmps 

I should probably work on it to avoid as much human error as possible like searching the entire directory you provide.
Currently I'm just adding the log directory on top of the directory you provide.
![image](https://github.com/alpharmi/wuthering.app/assets/50479738/c40c803f-c8f9-46ce-951c-7bdbae91642d)
So it's reading your directory like `F:\Games\Wuthering Waves Game\Wuthering Waves Game\Client\...`
So I'm assuming you have an additional "Wuthering Waves Game" folder within the other?

Cause mine looks something like so:
![image](https://github.com/alpharmi/wuthering.app/assets/50479738/6c139667-9a2d-4865-8689-1b7abb02049f)

> edit: Since the data is stored on the browser, maybe the user could paste the location to debug.log, and you generate a PowerShell command that grabs it? I am bellow junior so sorry if it was a bad suggestion.

The debug.log includes queries I need to call a different API, the actual site it brings up or the endpoint in the debug.log is quite useless.

**Comment by Miguelcmps** [comment]
@alpharmi Well, whatever you do/choose to do, I am happy with method 2. I am aware that I am not the average user though. 
This is my full path:
F:\Games\Wuthering Waves Game

![image](https://github.com/alpharmi/wuthering.app/assets/24736244/7381fbd0-5876-4807-8335-f6e233112665)

**Comment by alpharmi** [comment]
@Miguelcmps 

I've some changes, it should fix your problem with method 1.
Let me know how it goes.

**Comment by Miguelcmps** [comment]
@alpharmi 

It's working.
![image](https://github.com/alpharmi/wuthering.app/assets/24736244/dc724bfc-bcd3-4e60-8f62-1f2dcd345c9d)


(Please don't remove method 2, it's more pratical for me)

If you need anything else let me know.

**Comment by alpharmi** [comment]
@Miguelcmps 

I wont be removing method 2 don't worry.
Thanks for your help once again.

**Comment by EllaElla1** [comment]
> I've some changes, it should fix your problem with method 1. Let me know how it goes.

This has actually fixed my problem too! Now if i set the path as \Wuthering Waves Game it realises that I did give it the correct path and then goes on to correctly find the file

Thanks for your help!

**Comment by alpharmi** [comment]
@Miguelcmps @EllaElla1 Thank you both once again

**Comment by BestClaws** [comment]
I have a suggestion to reliably find the path
![image](https://github.com/alpharmi/wuthering.app/assets/40067018/4ad315df-a196-445b-8a07-1de415925a6d)
This could be an alternative method. but the only down side is, this requires script to run in elevated powershell as the game runs with elevated priviliges aswell to report the path or it's going to be empty.
