### ISSUE TITLE
Fetches pull history from different region (SEA) instead of the history from latest region (America).

### ISSUE THREAD

**Issue by enthalith** [alpharmi/wuthering.app#2]
Fetches pull history from different region (SEA) instead of the history from latest region (America).

I've accessed the history from the America account but no matter what I do, it's fetching from the SEA account.

**Comment by alpharmi** [comment]
I believe this is because I've only written the ps1 code to pull the first gacha log url, which is most likely your SEA one instead. I'll have a go at getting the latest.

**Comment by alpharmi** [comment]
If possible are you able to upload your debug.log from `GAME DIRECTORY\Wuthering Waves Game\Client\Binaries\Win64\ThirdParty\KrPcSdk_Global\KRSDKRes\KRSDKWebView`

Personally I don't have multiple region accounts so I need example data.

**Comment by enthalith** [comment]
Sure thing! Thanks!

[debug.log](https://github.com/alpharmi/wuthering.app/files/15450726/debug.log)

**Comment by alpharmi** [comment]
Thanks for sending over the log I appreciate it.
I can already see that there's 2 server ids, I'll get around to attempting to fix it now.

**Comment by alpharmi** [comment]
Are you currently playing on the region with Jiyan, Jianxin, and Calcharo, which should be America?
If so then I think the fix is done, I just want to double check with you if that's correct.

**Comment by enthalith** [comment]
Yup that's right. Thanks for the fix! Does it now default to the newest server id? And I can't access the old one anymore?

**Comment by alpharmi** [comment]
I've pushed the update, you can try on the site now.
It should just get the gacha for the region you last opened the log with.

**Comment by enthalith** [comment]
Seems to be working now! Thanks for the fix!
