### ISSUE TITLE
4 stars pity is not calculated correctly with 5 stars pulls in the mix

### ISSUE THREAD

**Issue by josephcaroe** [alpharmi/wuthering.app#5]
In this game sadly the 4 stars pity in the limited banner is reset when you get a 5 star. So this:

![image](https://github.com/alpharmi/wuthering.app/assets/14345195/ce627668-8f05-4b7e-b89c-5e381c84ff77)

Is wrong. in fact I did 5 pulls after this history, and I did not get a 4*, thus demonstrating the 4* counter was reset after getting Jiyan.

**Comment by alpharmi** [comment]
I'm assuming this applies to all banners, not just the character banner? If so I'll get to a fix immediately.

**Comment by josephcaroe** [comment]
I haven't been able to test this in other banners, but supposedly I'd say it works the same for all of them. I will get in touch again if I find any more information on this matter. Thanks for the quick response,  and good work on the website.

**Comment by alpharmi** [comment]
Wouldn't it just be a matter of updating the description of this to not say "Guaranteed at 10"
![image](https://github.com/alpharmi/wuthering.app/assets/50479738/a81e9571-db4d-4271-992d-3b9ee34b1914)
It's kinda hard to think of a solution here cause without pulling a 5 star, it's technically correct.

**Comment by josephcaroe** [comment]
I'd say the simplest thing would be to reset the counter (so in my case, 5* star pity and 4* star pity would be the same number) and keep the "Guaranteed at 10" indication, which is factually correct. 

Basically, whenever you make the calculation for the 4* star pity counter, you consider either the latest 4* or 5* pull.  This might complicate the 4* star aversge pity, which could get higher than 10.

**Comment by alpharmi** [comment]
![image](https://github.com/alpharmi/wuthering.app/assets/50479738/0272ad63-7608-4b2d-a32c-54c2ff3950ad)
I passed some sample data to test this.
Just want to double check this is what you meant when resetting the 4 star pity.

Regarding `Overture`, Kuro Games provides a different name in the logs then that it is displayed as in-game, so I'm still trying to find the corresponding image.

**Comment by alpharmi** [comment]
Ok I've pushed the pity reset fix, it should update when you re-import and I've added the overture image.

Thanks once again for your help.
